//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finances
    {
        public int OperationID { get; set; }
        public string OperationType { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
    }
}
