//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Losses
    {
        public int ClaimID { get; set; }
        public Nullable<int> PolicyID { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string ClaimStatus { get; set; }
        public string Description { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
